name: app-ansible
services: 
  control:
    build: .
    container_name: control
    command: ["tail", "-f", "/dev/null"]
    hostname: control
    volumes: 
      - .:/root/ansible

  node_ansible:
    build: .
    container_name: node_ansible
    command: ["tail", "-f", "/dev/null"]
    hostname: node_ansible